import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://chairbearlearning.github.io/projects/live-demos');
    await page.getByText('FCC RPG Creature Search').click();
    await expect(page.locator('#fcc-rpg-creature')).toContainText('FCC RPG Creature Search');
    await expect(page.getByText('FCC RPG Creature Search RPG')).toBeVisible();
    await expect(page.locator('#fcc-rpg-creature')).toContainText('What is this project?');
    await page.getByText('This project comes from the').click();
    await expect(page.locator('#fcc-rpg-creature')).toContainText('This project comes from the Free Code Camp, as one of the projects needed to gain a Javascript certification with them. See the project details on the FCC site - here');
    await expect(page.getByRole('link', { name: 'here' })).toBeVisible();
    await expect(page.locator('#fcc-rpg-creature')).toContainText('How to use?');
    await expect(page.locator('#fcc-rpg-creature')).toContainText('Select from the following, and enter to see the creatures details:');
    await expect(page.locator('#fcc-rpg-creature')).toContainText('Pyrolynx Aquoroc Terradon Beastmere');
    await expect(page.getByText('Search for Creature Name or ID: Search Base Stats HP: Attack: Defense: Sp.')).toBeVisible();
    await expect(page.getByRole('rowgroup')).toContainText('Base');
    await page.getByRole('cell', { name: 'Stats' }).click();
    await expect(page.getByRole('rowgroup')).toContainText('Stats');
    await expect(page.getByRole('rowgroup')).toContainText('HP:');
    await expect(page.getByRole('rowgroup')).toContainText('Attack:');
    await expect(page.getByRole('rowgroup')).toContainText('Defense:');
    await expect(page.getByRole('rowgroup')).toContainText('Sp. Attack:');
    await expect(page.getByRole('rowgroup')).toContainText('Sp. Attack:');
    await expect(page.getByRole('rowgroup')).toContainText('Sp. Defense:');
    await expect(page.getByRole('rowgroup')).toContainText('Speed:');
    await expect(page.locator('.name-and-id')).toBeVisible();
    await expect(page.locator('.top-rpg-container')).toBeVisible();
    await expect(page.getByText('Search for Creature Name or ID: Search')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Search' })).toBeVisible();
    await expect(page.locator('#search-form')).toContainText('Search for Creature Name or ID:');
    await expect(page.getByRole('textbox', { name: 'Search for Creature Name or' })).toBeVisible();
    await page.getByRole('textbox', { name: 'Search for Creature Name or' }).click();
    await page.getByRole('textbox', { name: 'Search for Creature Name or' }).fill('pyrolynx');
    await page.getByRole('button', { name: 'Search' }).click();
    await expect(page.locator('#creature-name')).toContainText('PYROLYNX');
    await expect(page.locator('#creature-id')).toContainText('#1');
    await expect(page.locator('#weight')).toContainText('Weight: 42');
    await expect(page.locator('#height')).toContainText('Height: 32');
    await expect(page.locator('#types')).toContainText('FIRE');
    await expect(page.locator('#hp')).toContainText('65');
    await expect(page.locator('#attack')).toContainText('80');
    await expect(page.locator('#defense')).toContainText('50');
    await expect(page.locator('#special-attack')).toContainText('90');
    await expect(page.locator('#special-defense')).toContainText('55');
    await expect(page.locator('#speed')).toContainText('100');
    await page.getByText('Beastmere').click();
    await page.getByRole('textbox', { name: 'Search for Creature Name or' }).click();
    await page.getByRole('textbox', { name: 'Search for Creature Name or' }).fill('');
    await page.getByRole('textbox', { name: 'Search for Creature Name or' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Search for Creature Name or' }).fill('BEASTMERE');
    await page.getByRole('button', { name: 'Search' }).click();
    await expect(page.locator('#creature-name')).toContainText('BEASTMERE');
    await expect(page.locator('#creature-id')).toContainText('#4');
    await expect(page.locator('#weight')).toContainText('Weight: 22');
    await expect(page.locator('#height')).toContainText('Height: 54');
    await expect(page.locator('#types')).toContainText('FAIRY');
    await expect(page.locator('#types')).toContainText('ELECTRIC');
    await expect(page.locator('#hp')).toContainText('155');
    await expect(page.locator('#attack')).toContainText('70');
    await expect(page.locator('#defense')).toContainText('19');
    await expect(page.locator('#special-attack')).toContainText('43');
    await expect(page.locator('#special-defense')).toContainText('45');
    await expect(page.locator('#speed')).toContainText('88');
    await page.getByRole('textbox', { name: 'Search for Creature Name or' }).click();
    await page.getByRole('textbox', { name: 'Search for Creature Name or' }).fill('testAlert');
    page.once('dialog', dialog => {
        console.log(`Dialog message: ${dialog.message()}`);
        dialog.dismiss().catch(() => {});
    });
    await page.getByRole('button', { name: 'Search' }).click();
});
